/*
 AngularJS v1.2.14
 (c) 2010-2014 Google, Inc. http://angularjs.org
 License: MIT
*/
(function(p,e,A){function x(q,l,k){return{restrict:"ECA",terminal:!0,priority:400,transclude:"element",link:function(a,d,b,g,w){function y(){m&&(m.remove(),m=null);n&&(n.$destroy(),n=null);h&&(k.leave(h,function(){m=null}),m=h,h=null)}function v(){var b=q.current&&q.current.locals;if(e.isDefined(b&&b.$template)){var b=a.$new(),c=q.current;h=w(b,function(c){k.enter(c,null,h||d,function(){!e.isDefined(t)||t&&!a.$eval(t)||l()});y()});n=c.scope=b;n.$emit("$viewContentLoaded");n.$eval(u)}else y()}var n,
h,m,t=b.autoscroll,u=b.onload||"";a.$on("$routeChangeSuccess",v);v()}}}function z(e,l,k){return{restrict:"ECA",priority:-400,link:function(a,d){var b=k.current,g=b.locals;d.html(g.$template);var w=e(d.contents());b.controller&&(g.$scope=a,g=l(b.controller,g),b.controllerAs&&(a[b.controllerAs]=g),d.data("$ngControllerController",g),d.children().data("$ngControllerController",g));w(a)}}}p=e.module("ngRoute",["ng"]).provider("$route",function(){function q(a,d){return e.extend(new (e.extend(function(){},
{prototype:a})),d)}function l(a,e){var b=e.caseInsensitiveMatch,d={originalPath:a,regexp:a},k=d.keys=[];a=a.replace(/([().])/g,"\\$1").replace(/(\/)?:(\w+)([\?\*])?/g,function(a,e,d,b){a="?"===b?b:null;b="*"===b?b:null;k.push({name:d,optional:!!a});e=e||"";return""+(a?"":e)+"(?:"+(a?e:"")+(b&&"(.+?)"||"([^/]+)")+(a||"")+")"+(a||"")}).replace(/([\/$\*])/g,"\\$1");d.regexp=new RegExp("^"+a+"$",b?"i":"");return d}var k={};this.when=function(a,d){k[a]=e.extend({reloadOnSearch:!0},d,a&&l(a,d));if(a){var b=
"/"==a[a.length-1]?a.substr(0,a.length-1):a+"/";k[b]=e.extend({redirectTo:a},l(b,d))}return this};this.otherwise=function(a){this.when(null,a);return this};this.$get=["$rootScope","$location","$routeParams","$q","$injector","$http","$templateCache","$sce",function(a,d,b,g,l,p,v,n){function h(){var c=m(),f=r.current;if(c&&f&&c.$$route===f.$$route&&e.equals(c.pathParams,f.pathParams)&&!c.reloadOnSearch&&!u)f.params=c.params,e.copy(f.params,b),a.$broadcast("$routeUpdate",f);else if(c||f)u=!1,a.$broadcast("$routeChangeStart",
c,f),(r.current=c)&&c.redirectTo&&(e.isString(c.redirectTo)?d.path(t(c.redirectTo,c.params)).search(c.params).replace():d.url(c.redirectTo(c.pathParams,d.path(),d.search())).replace()),g.when(c).then(function(){if(c){var a=e.extend({},c.resolve),b,d;e.forEach(a,function(c,b){a[b]=e.isString(c)?l.get(c):l.invoke(c)});e.isDefined(b=c.template)?e.isFunction(b)&&(b=b(c.params)):e.isDefined(d=c.templateUrl)&&(e.isFunction(d)&&(d=d(c.params)),d=n.getTrustedResourceUrl(d),e.isDefined(d)&&(c.loadedTemplateUrl=
d,b=p.get(d,{cache:v}).then(function(a){return a.data})));e.isDefined(b)&&(a.$template=b);return g.all(a)}}).then(function(d){c==r.current&&(c&&(c.locals=d,e.copy(c.params,b)),a.$broadcast("$routeChangeSuccess",c,f))},function(b){c==r.current&&a.$broadcast("$routeChangeError",c,f,b)})}function m(){var a,b;e.forEach(k,function(c,k){var f;if(f=!b){var g=d.path();f=c.keys;var l={};if(c.regexp)if(g=c.regexp.exec(g)){for(var h=1,n=g.length;h<n;++h){var m=f[h-1],p="string"==typeof g[h]?decodeURIComponent(g[h]):
g[h];m&&p&&(l[m.name]=p)}f=l}else f=null;else f=null;f=a=f}f&&(b=q(c,{params:e.extend({},d.search(),a),pathParams:a}),b.$$route=c)});return b||k[null]&&q(k[null],{params:{},pathParams:{}})}function t(a,b){var c=[];e.forEach((a||"").split(":"),function(a,d){if(0===d)c.push(a);else{var e=a.match(/(\w+)(.*)/),f=e[1];c.push(b[f]);c.push(e[2]||"");delete b[f]}});return c.join("")}var u=!1,r={routes:k,reload:function(){u=!0;a.$evalAsync(h)}};a.$on("$locationChangeSuccess",h);return r}]});p.provider("$routeParams",
function(){this.$get=function(){return{}}});p.directive("ngView",x);p.directive("ngView",z);x.$inject=["$route","$anchorScroll","$animate"];z.$inject=["$compile","$controller","$route"]})(window,window.angular);
